server:
  port: ${lyx.goods.port}

#dubbo
dubbo:
  application:
    name: lyx-goods
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882

mysql:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driverclass: com.mysql.cj.jdbc.Driver