server:
  port: ${lyx.web.port}

#dubbo
dubbo:
  application:
    name: web
  registry:
    address: zookeeper://127.0.0.1:2181

##Redis
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    timeout: 3000
    lettuce:
      pool:
        max-active: 100
        min-idle: 50
        max-wait: 2000