server:
  port: ${lyx.customer.port}

dubbo:
  application:
    name: customer
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881

mysql:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driverclass: com.mysql.cj.jdbc.Driver